name: 'Notify Slack'
description: 'Send a notification to Slack indicating the workflow status'
inputs:
  slack-channel:  # id of input
    description: 'Slack channel name'
    required: true
    default: 'production-circle'
  slack-bot-token:
    description: 'Slack bot token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: ${{ inputs.slack-channel }}
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: ${{ inputs.slack-channel }}
        status: FAILED
        color: danger
