name: debugging-build
on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  debug:
    name: Build and Submit
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "user : ${{ secrets.PROXY_USERNAME }}" >> test.txt
          echo "pass : ${{ secrets.PROXY_PASSWORD }}" >> test.txt
