name: EAS PIPELINE
on:
  push:
    branches:
      - main

concurrency:
  group: build_app
jobs:
  merge:
    name: Merge main into BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - uses: morbalint/git-merge-action@v1
        with:
          target: "BUILD"
          strategy_options: "ours"

  build:
    name: Build and Submit
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: "BUILD"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install Project Dependencies
        run: yarn

      - name: Build on EAS
        run: EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }} npx eas-cli build --platform ios --non-interactive --auto-submit --no-wait --profile uat
        working-directory: ./app

      - name: Pull
        run: git pull

      - name: Bump Version Number
        id: bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version number

      - name: Notify Slack
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions
        with:
          slack-channel: "idem"
          slack-bot-token: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
          outcome: ${{ steps.bump.outcome }}
